name: Using Private Repositroy Sample

on:
  pull_request:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout with submodule
      uses: actions/checkout@v1

    - name: hoge
      uses: ../actions/hoge

    - name: huga
      uses: ../actions/huga
